import { test, expect, type Page } from '@playwright/test'

const frame = (page: Page) => page.frameLocator('iframe')
const saved = (page: Page) => page.locator('.payload-panel pre')

async function eligible(page: Page) {
  await page.goto('/')
  await frame(page).getByRole('radio', { name: 'Yes', exact: true }).check()
  await frame(page).getByRole('button', { name: 'Save & Next' }).click()
  await expect(frame(page).getByLabel('Project name')).toBeVisible()
}

test('eligible assessment saves drafts, reloads, submits, and locks completed records', async ({ page }) => {
  await eligible(page)
  await frame(page).getByLabel('Project name').fill('Local export pilot')
  await frame(page).getByLabel('Risk level').selectOption('High')
  await frame(page).getByRole('checkbox').check()
  await frame(page).getByLabel('Target decision date').fill('2026-11-03')
  await frame(page).getByLabel('Assessment notes').fill('Reviewer context from the browser check')
  await expect(frame(page).getByText(/Unsaved changes/)).toBeVisible()
  await frame(page).getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(frame(page).getByText('Draft saved by the host.')).toBeVisible()
  await page.reload()
  await frame(page).getByRole('tab', { name: /Assessment/ }).click()
  await expect(frame(page).getByLabel('Project name')).toHaveValue('Local export pilot')
  await expect(frame(page).getByRole('checkbox')).toBeChecked()
  await frame(page).getByRole('button', { name: 'Save & Next' }).click()
  await frame(page).getByRole('button', { name: 'Submit JSON to host' }).click()
  await expect(saved(page)).toContainText('"status": "Validated"')
  await expect(saved(page)).toContainText('"submittedBy": "local-user"')
  await page.getByRole('button', { name: 'Mark completed' }).click()
  await expect(frame(page).getByText('Completed / Read-only')).toBeVisible()
  await frame(page).getByRole('tab', { name: /Assessment/ }).click()
  await expect(frame(page).getByLabel('Project name')).toHaveAttribute('readonly', '')
  await expect(frame(page).getByLabel('Risk level')).toBeDisabled()
  await expect(frame(page).getByRole('checkbox')).toBeDisabled()
  await expect(frame(page).getByRole('button', { name: 'Save draft' })).toHaveCount(0)
  await page.reload()
  await expect(frame(page).getByText('Completed / Read-only')).toBeVisible()
  await page.evaluate(() => {
    const source = document.querySelector('iframe')!.contentWindow!
    window.dispatchEvent(new MessageEvent('message', { source, origin: location.origin, data: { type: 'assessment-save', requestId: 'completed-save', payload: { recordId: 'ACME-LOCAL-APPLICATION-001', answers: { eligible: 'No' }, status: 'Draft' } } }))
  })
  await expect(saved(page)).toContainText('"status": "Completed"')
  const completed = await page.evaluate(() => JSON.parse(localStorage.getItem('jolisoft.assessment.v1.ACME-LOCAL-APPLICATION-001')!))
  expect(completed.status).toBe('Completed')
  expect(completed.answers.projectName).toBe('Local export pilot')
})

test('ineligible answer skips assessment and excludes stale assessment fields', async ({ page }) => {
  await eligible(page)
  await frame(page).getByLabel('Project name').fill('Discarded assessment')
  await frame(page).getByRole('tab', { name: /Eligibility/ }).click()
  await frame(page).getByRole('radio', { name: 'No', exact: true }).check()
  await frame(page).getByRole('button', { name: 'Save & Next' }).click()
  await expect(frame(page).getByRole('tab', { name: /Assessment/ })).toHaveAttribute('aria-disabled', 'true')
  await frame(page).getByRole('button', { name: 'Submit JSON to host' }).click()
  await expect(saved(page)).toContainText('"status": "Validated"')
  const payload = JSON.parse((await saved(page).textContent())!)
  expect(payload.answers).toEqual({ eligible: 'No' })
})

test('review navigation cannot bypass validation, and viewer access prevents saving', async ({ page }) => {
  await page.goto('/')
  await frame(page).getByRole('tab', { name: /Review/ }).click()
  await frame(page).getByRole('button', { name: 'Submit JSON to host' }).click()
  await expect(frame(page).getByRole('status')).toContainText('Please complete the assessment')
  await expect(saved(page)).not.toContainText('Validated')
  await frame(page).getByRole('tab', { name: /Eligibility/ }).click()
  await frame(page).getByRole('radio', { name: 'Yes', exact: true }).check()
  await frame(page).getByRole('button', { name: 'Save & Next' }).click()
  await frame(page).getByRole('tab', { name: /Review/ }).click()
  await frame(page).getByRole('button', { name: 'Submit JSON to host' }).click()
  await expect(frame(page).getByRole('status')).toContainText('Please complete the assessment')
  await page.getByLabel('Access').selectOption('read')
  await expect(frame(page).getByText('Draft / Read-only')).toBeVisible()
  await expect(frame(page).getByRole('radio', { name: 'Yes', exact: true })).toBeDisabled()
  await frame(page).getByRole('tab', { name: /Review/ }).click()
  await expect(frame(page).getByRole('button', { name: 'Submit JSON to host' })).toHaveCount(0)
})

test('unsaved reload can be cancelled and storage failures keep changes dirty', async ({ page }) => {
  await eligible(page)
  await frame(page).getByLabel('Project name').fill('Unsaved draft')
  await expect(frame(page).getByText(/Unsaved changes/)).toBeVisible()
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: 'Reload saved assessment' }).click()
  await expect(frame(page).getByLabel('Project name')).toHaveValue('Unsaved draft')
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('Simulated storage failure') } })
  await frame(page).getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(frame(page).getByRole('status')).toContainText('Simulated storage failure')
  await expect(frame(page).getByText(/Unsaved changes/)).toBeVisible()
})

test('host rejects invalid, wrong-origin, and unauthorized saves', async ({ page }) => {
  await page.goto('/')
  await expect(frame(page).getByRole('radio', { name: 'No', exact: true })).toBeVisible()
  await page.evaluate(() => {
    const source = document.querySelector('iframe')!.contentWindow!
    window.dispatchEvent(new MessageEvent('message', { source, origin: 'https://acme.invalid', data: { type: 'assessment-save', requestId: 'wrong-origin', payload: { recordId: 'ACME-LOCAL-APPLICATION-001', answers: { eligible: 'No' }, status: 'Validated' } } }))
    window.dispatchEvent(new MessageEvent('message', { source, origin: location.origin, data: { type: 'assessment-save', requestId: 'invalid', payload: { recordId: 'ACME-LOCAL-APPLICATION-001', answers: {}, status: 'Validated' } } }))
  })
  await expect(saved(page)).not.toContainText('Validated')
  await page.getByLabel('Access').selectOption('read')
  await expect(frame(page).getByText('Draft / Read-only')).toBeVisible()
  await page.evaluate(() => {
    const source = document.querySelector('iframe')!.contentWindow!
    window.dispatchEvent(new MessageEvent('message', { source, origin: location.origin, data: { type: 'assessment-save', requestId: 'viewer', payload: { recordId: 'ACME-LOCAL-APPLICATION-001', answers: { eligible: 'No' }, status: 'Validated' } } }))
  })
  expect(await page.evaluate(() => localStorage.getItem('jolisoft.assessment.v1.ACME-LOCAL-APPLICATION-001'))).toBeNull()
})

test('foundations editor preserves preview on invalid JSON, saves drafts, and applies custom validation', async ({ page }) => {
  await page.goto('/foundations.html')
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Draft saved locally without validation.')
  await page.getByRole('button', { name: 'Validate & Save' }).click()
  await expect(page.getByRole('status')).toContainText('Validation failed')
  await page.getByLabel('Project name').fill('Foundation project')
  await page.getByLabel('Risk level').selectOption('High')
  await page.getByRole('button', { name: 'Validate & Save' }).click()
  await expect(page.locator('.question-errors').getByText('High risk proposals need at least 10 characters of reviewer notes.', { exact: true })).toBeVisible()
  await page.getByLabel('Notes', { exact: true }).fill('Detailed reviewer notes')
  await page.getByRole('button', { name: 'Validate & Save' }).click()
  await expect(page.getByRole('status')).toHaveText('Validated and saved locally.')
  await page.getByLabel('JSON schema', { exact: true }).fill('{')
  await page.getByRole('button', { name: 'Apply schemas' }).click()
  await expect(page.getByLabel('Project name')).toHaveValue('Foundation project')
  await page.reload()
  await page.getByRole('button', { name: 'Load saved draft' }).click()
  await expect(page.getByLabel('Project name')).toHaveValue('Foundation project')
  const schema = JSON.parse(await page.getByLabel('JSON schema', { exact: true }).inputValue())
  schema.properties.projectName.title = 'Proposal title'
  await page.getByLabel('JSON schema', { exact: true }).fill(JSON.stringify(schema))
  await page.getByRole('button', { name: 'Apply schemas' }).click()
  await expect(page.getByLabel('Proposal title')).toHaveValue('Foundation project')
})
